### ISSUE TITLE
correction of coordinates of Time series

### ISSUE THREAD

**Issue by elfunesto** [ices-eg/wg_WGEEL#164]
* ImsaG 58.9037°N 5.96428°E (see Sandlund et al. 2017 and validated on google maps)
* InagGY: the current point is not on the Inagh river (red cross on map)
![Capture d’écran du 2020-09-13 13-07-52](https://user-images.githubusercontent.com/43066644/93017333-1272d000-f5c8-11ea-8f96-7b3601bf27ba.png)

**Comment by cedricbriandgithub** [comment]
-------------------------- uhhh ???? -------------------------------------------------------------
UPDATE datawg.t_series_ser SET geom=st_transform(ST_SetSRID(ST_MakePoint(-9.30116,52.9402),3857),4326) WHERE ser_nameshort='InagGY';
UPDATE datawg.t_series_ser SET (ser_x,ser_y)=(st_x(geom),st_y(geom)) WHERE ser_nameshort = 'InagGY';

SELECT ser_x FROM datawg.t_series_ser WHERE ser_nameshort='InagGY'; ---9.43
SELECT st_x(geom) FROM datawg.t_series_ser WHERE ser_nameshort='InagGY'; -- -9.43

-- en vrai c'est comme ça (google maps c'est du 3857) mais ça doit changer juste un chouilla, ci dessous avec 4326 seulement :

UPDATE datawg.t_series_ser SET geom=ST_SetSRID(ST_MakePoint(-9.30116,52.9402),4326) WHERE ser_nameshort='InagGY';
UPDATE datawg.t_series_ser SET (ser_x,ser_y)=(st_x(geom),st_y(geom)) WHERE ser_nameshort = 'InagGY';
-- pareil

SELECT ser_x FROM datawg.t_series_ser WHERE ser_nameshort='InagGY'; ---9.43
SELECT st_x(geom) FROM datawg.t_series_ser WHERE ser_nameshort='InagGY'; -- -9.43

-- Mais en direct ça marche
SELECT st_x(ST_SETSRID(ST_MakePoint(-9.30116,52.9402),4326)) -- -9.3
-- Celui là est correct
SELECT st_x(st_transform(ST_SetSRID(ST_MakePoint(-9.30116, 52.9402),3857),4326)) -- -9.35
-- Et c'est  pas un truc à la con genre j'ai deux lignes
SELECT * FROM  datawg.t_series_ser  WHERE ser_nameshort = 'InagGY'; -- one line
-- Et le point est bien en 4326
SELECT st_srid(geom) FROM  datawg.t_series_ser WHERE ser_nameshort='InagGY'; --4326 


-----------------------------------------------------------

**Comment by cedricbriandgithub** [comment]
NOW the bug is fixed I'm wondering if these corrections have ever been applied....
begin;
update datawg.t_series_ser SET geom=ST_SETSRID(ST_MakePoint(17.43453,60.55913),4326) WHERE ser_nameshort='Dala';
UPDATE datawg.t_series_ser SET (ser_x,ser_y)=(st_x(geom),st_y(geom)) WHERE ser_nameshort = 'Dala';
commit;


begin;
update datawg.t_series_ser SET geom=ST_SETSRID(ST_MakePoint(2.758001,51.134565),4326) WHERE ser_nameshort='Yser';
UPDATE datawg.t_series_ser SET (ser_x,ser_y)=(st_x(geom),st_y(geom)) WHERE ser_nameshort = 'Yser';
commit;

-- Göta Älv 58.27435, 12.27165
BEGIN;
UPDATE datawg.t_series_ser SET geom=ST_SETSRID(ST_MakePoint(12.27165,58.27435),4326) WHERE ser_nameshort='Gota';
UPDATE datawg.t_series_ser SET (ser_x,ser_y)=(st_x(geom),st_y(geom)) WHERE ser_nameshort = 'Gota';
COMMIT;


-- Kävlingeån 55.69855, 13.55370
BEGIN;
UPDATE datawg.t_series_ser SET geom=ST_SETSRID(ST_MakePoint(13.55370,55.69855),4326) WHERE ser_nameshort='Kavl';
UPDATE datawg.t_series_ser SET (ser_x,ser_y)=(st_x(geom),st_y(geom)) WHERE ser_nameshort = 'Kavl';
COMMIT;

-- Lagan 56.51565, 13.04992
BEGIN;
UPDATE datawg.t_series_ser SET geom=ST_SETSRID(ST_MakePoint(13.04992,56.51565),4326) WHERE ser_nameshort='Laga';
UPDATE datawg.t_series_ser SET (ser_x,ser_y)=(st_x(geom),st_y(geom)) WHERE ser_nameshort = 'Laga';
COMMIT;

-- Mörrumsån 56.39988, 14.66656
BEGIN;
UPDATE datawg.t_series_ser SET geom=ST_SETSRID(ST_MakePoint(14.66656,56.39988),4326) WHERE ser_nameshort='Laga';
UPDATE datawg.t_series_ser SET (ser_x,ser_y)=(st_x(geom),st_y(geom)) WHERE ser_nameshort = 'Laga';
COMMIT;

**Comment by cedricbriandgithub** [comment]
Tessa indicates that den oever was still wrong so I have at least applied this correction
-- change the Den Oever series, the location was really wrong
BEGIN;
UPDATE datawg.t_series_ser SET geom=ST_SETSRID(ST_MakePoint(5.327523,53.073100),4326) WHERE ser_nameshort='RhDO';
UPDATE datawg.t_series_ser SET (ser_x,ser_y)=(st_x(geom),st_y(geom)) WHERE ser_nameshort = 'RhDO';
commit;

**Comment by elfunesto** [comment]
all coordinates corrected
