### ISSUE TITLE
Annex 8 newdata eel_qal_id changed to 0 in downloaded newdata file

### ISSUE THREAD

**Issue by ciaraoleary** [ices-eg/wg_WGEEL#285]
For Annnex 8 i uploaded a file with 1 row of new data with eel_qal_id of 1 but when i downloaded the newdataseries file it had a eel_qal_id of 0.

data integration wouldn't let me upload until i had changed it back to 1
C

**Comment by cedricbriandgithub** [comment]
check if there is a constraint

**Comment by cedricbriandgithub** [comment]
I checked, it's not the problem but if there is no aquaculture don't try to provide a value. In the shiny there is a message if the qal_id is missing, in the db there is indeed a constraint, you cannot have qal_id 0 and missing value qal, I guess that using the minor case np instead of NP was the problem there
![image](https://github.com/ices-eg/wg_WGEEL/assets/26055877/af0cb6f2-7495-406a-b18f-c05a2e634f57)


```sql{
ALTER TABLE datawg.t_eelstock_eel ADD CONSTRAINT ck_qal_id_and_missvalue CHECK ((eel_missvaluequal IS NULL) or (eel_qal_id != 0));
```
