### ISSUE TITLE
problem with templates

### ISSUE THREAD

**Issue by elfunesto** [ices-eg/wg_WGEEL#315]
- [ ] need to repush the latest templates in github
- [ ] need to edit fi_idcou to fi_id_cou in annex time series and annex 10 in the readme, existing/delete/new/update individual metrics sheets

**Comment by cedricbriandgithub** [comment]
fi_idcou is in template while the name id db is fi_id_cou 
We fill in a void column in asking_data_update_series.R because of :
```r
line applyTemplateFormat <- function(templateformat, mydata){
  if(length(setdiff(names(templateformat), names(mydata)))>0) #on ajoute les colonnes manquantes
    mydata[,setdiff(names(templateformat), names(mydata))] = NA
  mydata <-  mydata %>%
    select(any_of(names(templateformat)))
  mydata  
}
```
and

line 431

```r
existing_metric <- applyTemplateFormat(formatted, existing_metric)
```
At that stage we have a fi_id_cou from the db that never makes it to the excel

Otherwise during integration in loading functions we have

```r
      data_xls <- readxlTemplate(path, sheet)
      if ("fi_idcou" %in% names(data_xls))
        data_xls <- data_xls %>%
          rename("fi_id_cou"=fi_idcou) #to deal with a bug
      cat("loading sheet ", sheet,"\n")
```

So we can read the data from the templates even if they are wrong (which happened to work last year)

@elfunesto have you done the edition of fi_id_cou in the templates ? Or should I do it.

**Comment by elfunesto** [comment]
yes, they were updated and pushed, that's why I had closed the issue
